version: '2.2'

services:

    portal:
        cpus: 2
        mem_limit: 2880m
        mem_reservation: 80m
        build: ./mpcontribs-portal
        env_file:
            - ./deployments/$DEPLOYMENT.env
        depends_on:
            - api
        volumes:
            - ./mpcontribs-portal/mpcontribs:/app/mpcontribs
            - /app/mpcontribs/portal/templates/notebooks/
            - ./mpcontribs-portal/webpack.config.js:/app/webpack.config.js
            - ./mpcontribs-portal/package.json:/app/package.json
            - ./mpcontribs-portal/wsgi.py:/app/wsgi.py
            - ./mpcontribs-portal/settings.py:/app/settings.py
        ports:
            - "8080:8080"
            - "8082:8082"
            - "8083:8083"

    api:
        cpus: 2
        mem_limit: 3400m
        mem_reservation: 600m
        build:
            context: ./mpcontribs-api
        depends_on:
            - redis
            - chrome
            - kernel_gateway
            #- xray
            #- mongo
            #- datadog
        volumes:
            - ./mpcontribs-api:/app
        env_file:
            - ./deployments/$DEPLOYMENT.env
        environment:
            FLASK_ENV: development
            MPCONTRIBS_MONGO_HOST: $MPCONTRIBS_MONGO_HOST
            #MPCONTRIBS_MONGO_HOST: mongo
            JUPYTER_GATEWAY_URL: http://kernel_gateway:8888
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_SNS_TOPIC_ARN: $AWS_SNS_TOPIC_ARN
            AWS_DEFAULT_REGION: us-east-1
        ports:
            - "5000:5000"
            - "5002:5002"
            - "5003:5003"

    chrome:
        build: mpcontribs-sidecars/chrome
        cpus: 2
        mem_limit: 2870m
        mem_reservation: 70m
        environment:
            - START_XVFB=false
        ports:
            - "4444:4444"

    kernel_gateway:
        cpus: 2
        mem_limit: 2850m
        mem_reservation: 50m
          #depends_on:
          #- orca
        env_file:
            - ./deployments/$DEPLOYMENT.env
        environment:
            KG_ALLOW_ORIGIN: '*'
        build: ./mpcontribs-sidecars/kernel_gateway
        ports:
            - "8888:8888"

              # orca:
              #     cpus: 2
              #     mem_limit: 3300m
              #     mem_reservation: 500m
              #     build: ./mpcontribs-sidecars/orca
              #     ports:
              #         - "9091:9091"

    # OTHER
    redis:
        image: redis:alpine
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    mongo:
        image: mongo:bionic
        ports:
            - "27017:27017"

    datadog:
      build: mpcontribs-sidecars/datadog-agent
      depends_on:
        - redis
      environment:
        - DD_API_KEY=$DD_API_KEY
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      ports:
        - "8125:8125/udp"

    docs:
        image: squidfunk/mkdocs-material:4.6.3
        command: serve --dev-addr=0.0.0.0:8081
        volumes:
            - .:/docs
        ports:
            - "8081:8081"

    jhub:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build:
            context: .
            dockerfile: binder/DockerfileJhub
        environment:
            - NODE_ENV=development
            - MAPI_KEY=$MAPI_KEY
            - DOCKER_NETWORK_NAME=mpcontribs_default
            - DOCKER_NOTEBOOK_DIR=/home/jovyan
        depends_on:
            - api
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - "8000:8000"

volumes:
  data-volume:
      driver_opts:
          type: none
          device: $PWD
          o: bind
